export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    INCREASE_BUY_ITEM: "INCREASE_BUY_ITEM",
    DECREASE_BUY_ITEM: "DECREASE_BUY_ITEM",
    DELETE_CART_ITEM: "DELETE_CART_ITEM",
    EMPTY_CART: "EMPTY_CART"
}